version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./promtail:/var/log
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
 
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\Users\VASU03\Documents\Grafana\Grafana\dummy_logs.py:/app/dummy_logs.py
      - C:\Users\VASU03\Documents\Grafana\Grafana\promtail\dummy.log:/app/dummy.log
    networks:
      - loki